### PR TITLE
Set asciidoctor-maven-plugin version to 1.5.3

### PR DESCRIPTION
**Pull request by jmini**
`asciidoctor-maven-plugin` 1.5.3 was released. See:
http://discuss.asciidoctor.org/1-5-3-2-release-Maven-plugin-tp4059p4120.html

Update of the pom files to use this version.

### CODE REVIEW

**Comment by abelsromero** [comment]
I think that the update script has some issue. Versions in sub-sub-projects are not updated :/
See projects in https://github.com/asciidoctor/asciidoctor-maven-examples/tree/master/java-extension-example

**Comment by mojavelinux** [comment]
The script doesn't recurse into subfolders which is why it misses these subprojects. A quick fix is just to manually update these for now, but an issue should be filed to enhance the script.

**Comment by jmini** [comment]
Thank you for the review... I will push a new version.

1. The groovy script can easelly be fixed by using `root.eachDirRecurse` (see [List files recursively](http://groovy-almanac.org/list-files-recursivly/))

2. I have properly tested this new version (`mvn clean` and then `mvn` at the root of the repo). The JRuby downgrade is still needed (pointers on the mailing list: [here](http://discuss.asciidoctor.org/Dot-Graphviz-format-in-Asciidoctor-diagram-in-a-maven-build-td4067.html) or [here](http://discuss.asciidoctor.org/1-5-3-2-release-Maven-plugin-tp4059p4103.html)). I was too quick yesterday...

**Comment by abelsromero** [comment]
Everything is fine for me, I say :+1:

**Comment by mojavelinux** [comment]
:+1:

**Pull request merged**
