### PR TITLE
updated 'asciidoc-to-pdf-example' to use asciidoctorj-pdf and diagram's readme revision

### PR DESCRIPTION
**Pull request by abelsromero**
This PR includes:

. *Updated 'asciidoc-to-pdf-example' to use asciidoctorj-pdf*: just updated the pom to use the current version of _asciidoctorj-pdf_ instead of using the old method of including the gem _asciidoctor-pdf_. The purpouse of this change is to update all examples to the latest version and usage of asciidoctorj-*.

. *Added a note about usage of `dot` command to asciidoctor-diagram-example's README*: to execute the diagram example the Graphviz command tools must be installed. This is clearly stated in the following article: http://asciidoctor.org/news/2014/02/18/plain-text-diagrams-in-asciidoctor/, but not in the example. I think it's nice to offer the information and the reference to the article here too.

### CODE REVIEW

**Comment by mojavelinux** [comment]
Fantastic! I'll let you do the honors of merging.

**Comment by mojavelinux** [comment]
>  I think it's nice to offer the information and the reference to the article here too.

I agree!

**Comment by tduchateau** [comment]
Works like a charm. Thanks!

**Comment by mojavelinux** [comment]
\o/ Thanks for testing!

**Pull request merged**
