### PR TITLE
Version update and showing how to set the JRuby version

### PR DESCRIPTION
**Pull request by abelsromero**
This PR includes as main changes:
* Updated plugin version to latest. From 1.5.2 to 1.5.2.1
* Added JRuby dependency in all plugin's configurations (site too)
* Added note on README.adoc about JRuby dependency

And also, the minnor fixes:
* Updated asciidoctorj-pdf dependency to latest in 'multiple-inputs'
* Fixes corrupted quotes in README, back to UTF-8

### CODE REVIEW

**Comment by mojavelinux** [comment]
Nice!

I noticed you have some inconsistent formatting (tabs instead of spaces). Could you double check that? We want to be consistent about indenting with 4 spaces. Perhaps even mention that in the README so that contributors know.

**Comment by abelsromero** [comment]
No problem at all! I've seen that in some files and I set my IDE to use spaces already but old files/sections have not ben updated.

Just when I saw that, I thought about setting [chestyle maven plugin](https://maven.apache.org/plugins/maven-checkstyle-plugin/) but I'm afraid that could discourage contributions.
wtdyt? maybe set a handfull of rules, no more than 4 or 5.

**Comment by mojavelinux** [comment]
> maybe set a handfull of rules, no more than 4 or 5.

Indeed. Best is to put in the rules we monitor and leave the rest out. In other words, opt-in. That way, it shouldn't annoy contributors anymore than we'd already do it in the code review ;)

**Comment by mojavelinux** [comment]
👍

**Pull request merged**
