### PR TITLE
adopt asciidoctorj-diagram in asciidoctor-diagram-example 

### PR DESCRIPTION
**Pull request by madmas**
As of https://github.com/asciidoctor/asciidoctorj/pull/271 there would be a *J wrapper for asciidoctor-diagram. 

This PR integrates that into the samples (thus it will not work before asciidoctorj-diagram's PR integrated...)

Done by @maximmo and @madmas during Hackergarten Basel :)

### CODE REVIEW

**Comment by LightGuard** [comment]
Isn't this missing the jruby dependency?

**Comment by tduchateau** [comment]
The `asciidoctorj-diagram` artifact doesn't seem to be available in Central: http://search.maven.org/#search%7Cga%7C1%7Corg.asciidoctor.

Am I missing something?

**Comment by abelsromero** [comment]
It's not published yet, in fact it's not even merged in asciidoctorj/master. This is an addition done in tonight's hackergarten at Basel.

I asked Alex if he can publish a preview in bintray so that this example can work, but currently can only work if you install  asciidoctorj-diagram locally from sources. I guess he'll look at it tomorrow (it's 23:40 now here).

**Comment by tduchateau** [comment]
Great news!

I guess 'll wait for the release in Central :-)

**Comment by mojavelinux** [comment]
> I asked Alex if he can publish a preview in bintray so that this example can work

We really should be publishing snapshots to oss.jfrog.org. I just didn't get around to setting it up when I did the migration to Gradle. Perhaps it's time to look into it. I would rather be publishing snapshots for these types of things than hurrying a preview release out the door.

**Comment by abelsromero** [comment]
If we achieve that, would it be better to configure the snapshots with a profile? I think it is important to separate the stable code from the most recent to avoid confusions.

**Comment by mojavelinux** [comment]
> If we achieve that, would it be better to configure the snapshots with a profile?

Absolutely. Or, we could use SNAPSHOTs only in a branch / pull request for testing purposes and only merge when a release is available. (or we could employ a combination strategy). I think we can agree SNAPSHOTs in the master of this repo would not be good.

**Comment by jmini** [comment]
I have proposed a new version of this pull request: #37

**Comment by madmas** [comment]
thanks to @jmini, the changes of this PR got included in #37 so I close this PR

**Comment by mojavelinux** [comment]
:+1: Teamwork!

**Pull request closed without merging**
