### PR TITLE
Update root pom.xml to add the module "java-extension-example"

### PR DESCRIPTION
**Pull request by jmini**
As discussed in PR #20, this is an additional modification for the root `pom.xml` file and its documentation in the root `README.adoc` file.

### CODE REVIEW

**Comment by abelsromero** [comment]
I think all the important ideas are there, but I would have written it in a different style.
I'm not 100% sure either, but to make the readme more fluent, we could extend the intro "Getting the examples" in this manner:
* Talk a bit about the structure after the current text mentioning that there's a parent POM to ease testing and combined execution, and that examples can be executed all at once from it, or 100% separatly.
* Add the usage sub-section as it is, just fixing the command. The descripcion is correct, but the command states just `mvn` instead of  `mvn compile'.

Before any change, just wait for what @mojavelinux has to say. It wont' be the first time we 'constructively' disagree.

**Comment by mojavelinux** [comment]
Agreed on both counts. I also think we can soften the introduction text to be more focused on the informative part. Something like:

“The root pom.xml (aggregate build) is provided to allow you to run all the example projects at once using a single invocation of Maven. It also drives the continuous integration (CI) build. The root pom.xml does not contain any shared build configuration so that each of the projects can be used independently. This makes the examples suitable as independent references and as a starting point for your own project.”

As for the usage sub-section, the command can just be `mvn`, not `mvn compile` because @jmini added a default goal to the root pom.xml. So either command will work.

**Comment by mojavelinux** [comment]
Hahaha, I guess after my revisions I ended up only agreeing on the first count :)

**Comment by abelsromero** [comment]
Agree :+1:

**Comment by jmini** [comment]
Commit 59d1e680d49beec6b5e51c65615444eb284d5428 amened with your feedback.

**Comment by mojavelinux** [comment]
:+1:

**Comment by mojavelinux** [comment]
Thanks @jmini & @abelsromero!

**Pull request merged**
