### PR TITLE
Asciidoctor Maven plugin - revealjs example

### PR DESCRIPTION
**Pull request by kubamarchwicki**
This is a sample configuration how to get Asciidoctor Maven plugin running with revealjs and asciidoctor-revealjs backend. 
This is obviously inspired by the appropriate gradle plugin.

### CODE REVIEW

**Comment by abelsromero** [comment]
I only have one minnor appreciation:
. `docinfo.html` is not used rigth? I mean, it could be deleted.

Other than that is great :+1: You even took some time to comment the pom.xml.

**Comment by kubamarchwicki** [comment]
Right. As I copied whole example code from gradle plugin examples I blindly copied the `docinfo.html`. It's note used explicitly anywhere. 
I tried to comment less tricky parts of pom. Glad I could help

**Comment by abelsromero** [comment]
My mistake, sorry, I saw something else to fix.
Could you update the list of examples in the main README (https://github.com/asciidoctor/asciidoctor-maven-examples/blob/master/README.adoc)?

Also, if it's not a lot to ask. When everything is done, just squash the changes and we are good to merge.

Thanks,

**Comment by mojavelinux** [comment]
Thanks for preparing this pull request @kubamarchwicki!

Before we merge, there's on change I'd like to propose. I don't think we need the whole gem dependency and configuration part. AsciidoctorJ bundles the necessary gems to use templates, so just AsciidoctorJ should be enough.

I sent a pull request to your pull request with proposed changes.

I also think we should rename example-manual.adoc to deck.adoc or slides.adoc so as to make the intent more clear.

**Comment by kubamarchwicki** [comment]
Thank you guys. Remarks, code review and notes applied. Squashed with a pleasure :)

**Comment by mojavelinux** [comment]
Looks solid to me! Good work, @kubamarchwicki.

**Pull request merged**
