### PR TITLE
Use "asciidoctorj-diagram" instead of "asciidoctor-diagram"

### PR DESCRIPTION
**Pull request by jmini**
I think that it solves #34 

@madmas:
This pull request is based on your work started in Pull Request #12.
I have rebased your change on master and updated to the new versions.
Thank you for that!

Related topic on the mailing list:
http://discuss.asciidoctor.org/Asciidoctor-Maven-Plugin-asciidoctor-diagram-vs-asciidoctorj-diagram-td4076.html

### CODE REVIEW

**Comment by mojavelinux** [comment]
Looks good to me!

**Comment by madmas** [comment]
Look good for me, too :+1: thank you

I closed PR #12 .

**Comment by abelsromero** [comment]
:+1: I can merge if we all agree.

**Comment by jmini** [comment]
:+1: Thank you in advance.

**Comment by mojavelinux** [comment]
:+1:

**Pull request merged**
