### PR TITLE
Added site.xml and Ghostscript Tiger

### PR DESCRIPTION
**Pull request by staylorx**
I added a site.xml file to wire the Maven site content to the rendered asciidoctor page.
Updated the readme to point to the index.html to show off the top-level Maven site.
Added an image to the hello.ad page including attribution.
I added a reporting section to the pom (with encoding property) to remove one of the warnings from the build.

### CODE REVIEW

**Comment by mojavelinux** [comment]
Excellent. Only one small change request remaining. Could you rename the image file to `tiger.png` just to keep it simple? You can just push again to the same branch to update the pull request. Thanks!

**Comment by staylorx** [comment]
Will do... and thanks for the info re the same pull request. I got excited.

**Comment by abelsromero** [comment]
For me, this is all great :+1:

**Comment by staylorx** [comment]
Cool. Thanks!

**Comment by mojavelinux** [comment]
Thank you @staylorx!

**Pull request merged**
