### PR TITLE
Asciidoctor Maven plugin - deckjs example

### PR DESCRIPTION
**Pull request by kubamarchwicki**
This is a sample configuration how to get Asciidoctor Maven plugin running with deckjs and asciidoctor-deckjs backend. As I've been recently doing this for one of my projects - I think some people may find it useful.
This is obviously inspired by the appropriate gradle plugin.

### CODE REVIEW

**Comment by mojavelinux** [comment]
This is great! However, is there a reason you're using deck.js over reveal.js? I'd rather see an example added that uses reveal.js as it starts people off on the right foot. Still, if deck.js is important to you, I'm happy to merge this.

**Comment by kubamarchwicki** [comment]
Can I reverse the question? Why you favour reveal.js over deck.js? :)

I have no strong feeling about either. I use both. Reveal / DZslides works for me conference presentations. Deckjs is a bit powerpoint'ish and covers with my traning side of thing. 
It just happened I was fiddling with deckjs hence the sample. I can provide a reveal.js example as well. The whole example should work be pretty much the same.

**Comment by mojavelinux** [comment]
My opinion is that deck.js is very poorly done and woefully outdated. While it's true that it lends itself well to making PowerPoint-style layouts, that can be achieved by any modern HTML5 presentation tool with the right theme, reveal.js included. Where deck.js falls down is that it has no ability to scale the presentation sensibly so it ends up being very dependent on the screen size on which it was designed. It also styles presentations in a way that looks very ugly to me.

Reveal.js leans towards being very monolithic, but at least it leverages the full power of HTML5 to make the presentation look consistent across screens and comes with more sensible themes out of the box.

My favorite is actually neither of these, but an up-and-coming tool named bespoke.js. I'm starting to work on a new backend for it and will be publishing my impressions about it soon.

**Comment by mojavelinux** [comment]
To help you understand where I'm coming from here a bit better, I'm not saying that deck.js can't be made to work. I'm saying that if we make an example with it, and that example uses what deck.js provides out of the box, then we will be leading people down the wrong path. While reveal.js isn't perfect, I think at least it's the better of the two paths.

**Comment by kubamarchwicki** [comment]
Thank you Dan. Very insightful explanation. This also means I need a better understanding of reveal.js and it themes :) 

I'll close this pull request and do another one with reveal. Shouldn't be that hard after all

**Comment by mojavelinux** [comment]
Sweet! I look forward to it.

**Pull request closed without merging**
