### PR TITLE
upgrade AsciidoctorJ 2.1.0, Asciidoctorj-pdf 1.5.0-beta.6, jRuby 2.1.8.0

### PR DESCRIPTION
**Pull request by abelsromero**

### CODE REVIEW

**Comment by mojavelinux** [comment]
Looks good!

One minor thing. The commit message says "jRuby 2.1.8.0" but should say "JRuby 9.2.8.0".

**Comment by abelsromero** [comment]
I found some issues I need to look into:
* kindlegen not being found when it is in path
* cjk example: error while converting, seems an API incompatibility
* pdf with theme -> front page layout is not showing correctly since beta.2 version

> One minor thing. The commit message says "jRuby 2.1.8.0" but should say "JRuby 9.2.8.0".

Sure thing, I'll probably rename the branch an all when everything is ready.

**Comment by abelsromero** [comment]
Note about cjk-pdf, the issue appears with asciidoctorj-pdf-beta.2 (beta.1 was not released).
```
Caused by: org.asciidoctor.jruby.internal.AsciidoctorCoreException: org.jruby.exceptions.TypeError: (TypeError) nil can't be coerced into Float
    at org.asciidoctor.jruby.internal.JRubyAsciidoctor.convertFile (JRubyAsciidoctor.java:391)
    at org.asciidoctor.jruby.internal.JRubyAsciidoctor.convertFile (JRubyAsciidoctor.java:362)
    at org.asciidoctor.maven.AsciidoctorMojo.renderFile (AsciidoctorMojo.java:476)
    at org.asciidoctor.maven.AsciidoctorMojo.execute (AsciidoctorMojo.java:260)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.jruby.exceptions.TypeError: (TypeError) nil can't be coerced into Float
    at org.jruby.RubyFloat.- (org/jruby/RubyFloat.java:335)
    at RUBY.move_down (uri:classloader:/gems/prawn-2.2.2/lib/prawn/document.rb:448)
    at RUBY.move_down (uri:classloader:/gems/asciidoctor-pdf-1.5.0.beta.2/lib/asciidoctor-pdf/prawn_ext/extensions.rb:450)
    at RUBY.convert_document (uri:classloader:/gems/asciidoctor-pdf-1.5.0.beta.2/lib/asciidoctor-pdf/converter.rb:213)
    at org.jruby.RubyBasicObject.instance_exec (org/jruby/RubyBasicObject.java:2680)
    at RUBY.dry_run (uri:classloader:/gems/asciidoctor-pdf-1.5.0.beta.2/lib/asciidoctor-pdf/prawn_ext/extensions.rb:840)
    at RUBY.font (uri:classloader:/gems/prawn-2.2.2/lib/prawn/font.rb:62)
    at RUBY.save_font (uri:classloader:/gems/prawn-2.2.2/lib/prawn/font.rb:215)
    at RUBY.font (uri:classloader:/gems/prawn-2.2.2/lib/prawn/font.rb:60)
    at RUBY.font (uri:classloader:/gems/asciidoctor-pdf-1.5.0.beta.2/lib/asciidoctor-pdf/prawn_ext/extensions.rb:192)
    at RUBY.dry_run (uri:classloader:/gems/asciidoctor-pdf-1.5.0.beta.2/lib/asciidoctor-pdf/prawn_ext/extensions.rb:839)
    at RUBY.convert_document (uri:classloader:/gems/asciidoctor-pdf-1.5.0.beta.2/lib/asciidoctor-pdf/converter.rb:211)
    at RUBY.convert (uri:classloader:/gems/asciidoctor-pdf-1.5.0.beta.2/lib/asciidoctor-pdf/converter.rb:134)
    at RUBY.convert (uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:951)
    at RUBY.convert (uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:118)
    at RUBY.convert_file (uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183)
    at org.jruby.RubyIO.open (org/jruby/RubyIO.java:1158)
    at RUBY.convert_file (uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183)
```

**Comment by mojavelinux** [comment]
The cjk gem shouldn't be required anymore. Setting the `script=cjk` attribute will enable this behavior out of the box. And the `pdf-theme=default-with-fallback-font` should cover a bulk of the characters. (Though a gem that provided a full CJK font would still be very useful).

**Comment by mojavelinux** [comment]
> pdf with theme -> front page layout is not showing correctly since beta.2 version

I think you mean the title page layout. The align attribute is now required:

```
title_page:
  background_image: image:cover.png[align=top]
```

**Comment by abelsromero** [comment]
> I think you mean the title page layout. The align attribute is now required:
> 
> ```
> title_page:
>   background_image: image:cover.png[align=top]
> ```

This doesn't seem to work, but I found an alternative way:

```
title_page:
  logo:
    image: image:cover.png[]
    top: 0%
```

**Comment by abelsromero** [comment]
> And the `pdf-theme=default-with-fallback-font` should cover a bulk of the characters. (Though a gem that provided a full CJK font would still be very useful).

I finally added the configuration to download the fonts and themes for `asciidocotr-pdf-cjk` and added an explanation in the README to explain that gems are not compatible, we only use the resources. Thing is that using `default-with-fallback-font` I found there were missing characters in the chinese doc, and the Japanase introduced additional spaces in the text (at first I though these were missing until I compared the text with the original).

Let me know if you thing this not a good approach, maybe we can add extra executions using only `default-with-fallback-font` so that people can compare and know how to start?


Only need to fix the kindlegen example and we'll be ready to go :smiley:

**Comment by mojavelinux** [comment]
> In my example, I used the wrong attribute. It should be position, not align.

```
title_page:
  background_image: image:cover.png[position=top]
```

> This doesn't seem to work, but I found an alternative way:

Keep in mind the background image is different than the title logo. The title logo is placed on the title page, but can't stretch and has limited positioning. The background image can be stretched and positioned, but it doesn't take up space.

**Comment by mojavelinux** [comment]
> Thing is that using default-with-fallback-font I found there were missing characters in the chinese doc

That's true. The fallback covers a basic set, but not all of it.

> I finally added the configuration to download the fonts and themes for asciidocotr-pdf-cjk and added an explanation in the README to explain that gems are not compatible, we only use the resources. 

That's correct. I merged the code from that gem into the converter, but it is still needed for the fonts.

**Comment by abelsromero** [comment]
This is the final PR with all bur epub3 fixed.
For epub3 I updated the current issue https://github.com/asciidoctor/asciidoctor-maven-examples/issues/77 and the README.

**Pull request closed without merging**
