### PR TITLE
Adds an epub example (Issue gh-56)

### PR DESCRIPTION
**Pull request by rladstaetter**

### CODE REVIEW

**Comment by abelsromero** [comment]
Hi Robert,
Love the exampe, but I a have a doubt. I think the example only has one chapter, is that on purpose?
iirc, epubs need to set a full asciidoc file for each chapter, maybe we can split the sections in different files to show that.

Also, I could not building the mobi on Windows, what platform are you using?
Btw, I filled an issue, just in case you want to add something: https://github.com/asciidoctor/asciidoctor-epub3/issues/154.

**Comment by rladstaetter** [comment]
Now I've added additional chapters, the reason was that I tried to stick with the example-manual template and didn't want to invent something fancy.

Mobi generation works more or less under macosx. You have to set KINDLEGEN env var to the executable. 

If you uncomment the second execution block, following message occurs:

```
[ERROR] Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.5.6:process-asciidoc (generate-spine-kf8) on project asciidoctor-epub-example: Execution generate-spine-kf8 of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.6:process-asciidoc failed: org.jruby.exceptions.RaiseException: (Errno::ECHILD) No child processes -> [Help 1]
```

Anyhow, the mobi file gets generated.

**Comment by abelsromero** [comment]
> Mobi generation works more or less under macosx. You have to set KINDLEGEN env var to the executable.

I saw the comment in the pom and it doesn't surprise me...Gems, jRuby, Java, Maven and kindlegen...too many moving pieces. Just curious, if you run `mvn -e` what is the full stacktrace you get?

Btw, I am trying to get it working on Windows and I get other errors :disappointed:, but I am sure we can get both cases working flawlesly, or at leas narrow the problem and report it.

**Comment by abelsromero** [comment]
Btw, so far I don't see any other issue with the PR. I'll leave it open for a day just in case someone else wants to add something.

**Comment by rladstaetter** [comment]
if kindlegen is in PATH or env variable KINDLEGEN is set and if I uncomment the execution block with id 'generate-spine-kf8', I get following exception:

```
[ERROR] Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.5.6:process-asciidoc (generate-spine-kf8) on project asciidoctor-epub-example: Execution generate-spine-kf8 of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.6:process-asciidoc failed: org.jruby.exceptions.RaiseException: (Errno::ECHILD) No child processes -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.5.6:process-asciidoc (generate-spine-kf8) on project asciidoctor-epub-example: Execution generate-spine-kf8 of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.6:process-asciidoc failed: org.jruby.exceptions.RaiseException: (Errno::ECHILD) No child processes
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution generate-spine-kf8 of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.6:process-asciidoc failed: org.jruby.exceptions.RaiseException: (Errno::ECHILD) No child processes
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: org.asciidoctor.internal.AsciidoctorCoreException: org.jruby.exceptions.RaiseException: (Errno::ECHILD) No child processes
	at org.asciidoctor.internal.JRubyAsciidoctor.renderFile(JRubyAsciidoctor.java:347)
	at org.asciidoctor.maven.AsciidoctorMojo.renderFile(AsciidoctorMojo.java:412)
	at org.asciidoctor.maven.AsciidoctorMojo.execute(AsciidoctorMojo.java:228)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
Caused by: org.jruby.exceptions.RaiseException: (Errno::ECHILD) No child processes
´´´

**Comment by rladstaetter** [comment]
improved cover for epub3 and .mobi generation.

**Comment by rladstaetter** [comment]
concerning the exception above: because of this i'm helping myself by calling kindlegen directly with maven-exec-plugin, bypassing 'kf8' mode from ascidoctor-epub3. i compared both epub files which are generated, there are some - but so far it works for me. 

in my opinion, kindlegen should not be called directly by asciidoc-epub3, at least one should be able to just generate a 'xxxx-kf8.epub' file which could then later be processed by kindlegen. like this there is a little less magic involved (resolving kindlegen by env var or path) and its more idiomatic for the build systems involved (maven, gradle are made for stuff like calling programs a before b before c ... 

...  my 0.02 cents

**Comment by abelsromero** [comment]
> concerning the exception above: because of this i'm helping myself by calling kindlegen directly with maven-exec-plugin, bypassing 'kf8' mode from ascidoctor-epub3.

I don't have a kindle to check but looking into the code of the epub3 converter, I see some changes in the css adjusments when the format is `kf8`. So, there's definitely something there that kindlegen does not fix. Maybe @mojavelinux can add more details?
As for me, I don't see as a bad option to add the exec-plugin here with a note that this an alternative in case of issues with the build. I couldn't make it run on Windows either, and I think it's due to a issue with jRuby.
Tomorrow I'll check on MacOS.

> one should be able to just generate a 'xxxx-kf8.epub' file which could then later be processed by kindlegen

Probably, the idea is offer a simple experience to writters. Keep in mind that not all Asciidoctor users are tech people, and one of the main goals of the project is to offer a very easy start and "good defaults" for documentation.
But in any case, I am 100% sure Dan will appreciatte any feedback. Maybe there's another approach to the matter none of us have thought of.

**Comment by rladstaetter** [comment]
> Probably, the idea is offer a simple experience to writters. Keep in mind that not all Asciidoctor users are tech people, and one of the main goals of the project is to offer a very easy start and "good defaults" for documentation.
I agree 😊.

**Comment by abelsromero** [comment]
I tester your branch on MacOS and the `ECHILD` issue can be fixed just upgrading the version of jRuby to 9.1.8.0. yay!
So... we can add the a comment on the jRuby version stating that kf8 format requires jRuby >= 9.1.8.0.
And add the maven-exec-plugin commented as a possible workaround for execution issues on Windows. wyt?

I promise that's all ! ^_^ I know I can be a PINA perfectionist, thanks.

**Comment by rladstaetter** [comment]
i've restructured the pom in order to execute asciidoctor-epub3 gem with kf8 usage now. 

maven exec plugin is commented out as fallback.

**Comment by abelsromero** [comment]
Perfect! I'll merge in 24h just in case someone else wants to add something.

**Comment by rladstaetter** [comment]
👍 :)

**Pull request merged**
