### PR TITLE
Add "extension-example" (an asciidoctorj extension written in java)

### PR DESCRIPTION
**Pull request by jmini**
This is based on the article published by @mrhaki:
[Awesome Asciidoctor: Write Extensions Using Groovy (or Java)](
http://mrhaki.blogspot.ch/2014/08/awesome-asciidoc-write-extensions-using.html)
I rewrote the groovy example in java and put it in a normal maven project.

Related discussion: [example of an asciidoctorj extension using java and maven](
http://discuss.asciidoctor.org/example-of-an-asciidoctorj-extension-using-java-and-maven-td3370.html).

Disclamer: I am not a maven expert (and still in the process of learning asciidoctor). Please review my setup.

### CODE REVIEW

**Comment by jmini** [comment]
I amended commit 7a4deee434ee145b831da0a8174fa6e135221a8a to add theses changes:

* rename the project to `java-extension-example`.
* update the root README file.

**Comment by mojavelinux** [comment]
:+1:

**Comment by abelsromero** [comment]
Just a small comment. I think it would be nice to add a few words in the documentation stating it uses the [SPI interface](https://github.com/asciidoctor/asciidoctorj#extension-spi). Is it possible?
Version 1.5.2.1 of the plugn includes other options to register extensions and we may extend the examples in the future with them.

Other that than, great example :+1:

**Comment by jmini** [comment]
@abelsromero: if there is a best pratice (or a "prefered way"), the examples in this repo should use it.

But: all examples use `1.5.2` and not `1.5.2.1`. 

I looked on [maven central](http://search.maven.org/#search|ga|1|a:%22asciidoctorj%22). The latest available version is `1.5.2`. The examples we provide in this repo needs to use this version in order to be easy to use.

Maybe we should capture your idea in a new issue and apply it when we migrate the examples to `1.5.2.1`,  `1.5.3` or `1.6.0`. (When it is released on maven central).

**Comment by mojavelinux** [comment]
1.5.2.1 is available and we should definitely upgrade the examples to use it. See http://search.maven.org/#artifactdetails%7Corg.asciidoctor%7Casciidoctor-maven-plugin%7C1.5.2.1%7Cmaven-plugin

The search in Maven often gets the latest version numbers mixed up, so watch out for that in general.

(As I side note, I also think we need to get the jruby.version property actually working so it can be used to control the version of JRuby used in all the examples).

**Comment by abelsromero** [comment]
> (As I side note, I also think we need to get the jruby.version property actually working so it can be used to control the version of JRuby used in all the examples).

If I understand what you mean, it's really easy to do. All examples include a `<jruby.version>` property, so it's only a matter of adding this to the plugin's dependency block in each example.
```
        <dependencies>
            <dependency>
                <groupId>org.jruby</groupId>
                <artifactId>jruby-complete</artifactId>
                <version>${jruby.version}</version>
            </dependency>
        </dependencies>
```
Also, the [script](https://github.com/asciidoctor/asciidoctor-maven-examples#updating-asciidoctor-maven-plugin-version) to update the plugin version can already update the jruby property too, it just updates all properties ended with 'version'.

If it's OK for you both, we can merge this issue today and update the poms to include the jruby dependency in another PR. wdyt?

**Comment by mojavelinux** [comment]
Spot on! I think the jruby.version thing just wasn't finished yet.

Yes, please merge!

**Comment by abelsromero** [comment]
Hi,

While updating the examples to add the jruby dependency I found that the aggregator example fails when invoked from the parent with some phases.
Doing just `mvn` or `mvn package` works, doing `mvn generate-resources` or `mvn process-resources` doesn't. 
According to the message, it tries to download the twitter extension from maven repo instead of using the local version...prettty weird to me. Any idea?

**Comment by mojavelinux** [comment]
This may just be a limitation of Maven. It may not setup the reactor properly if you don't go all the way to the package phase on each subproject.

**Comment by mojavelinux** [comment]
It looks like the compile goal is enough. Probably because it can't use the other module until it is at least compiled.

**Comment by mojavelinux** [comment]
So we need to recommend that you at least run compile from the root (or no goal and it will use the defaultGoal for each submodule).

```
$ mvn compile
```

or

```
$ mvn
```

**Comment by mojavelinux** [comment]
Btw, the java-extension-example is missing from the root pom.xml. Or were you waiting to add it until you figured out why it was using a snapshot?

**Comment by jmini** [comment]
I was not aware about this root `pom.xml` file (I have always looked at the example one by one).

I am not sure to know what you mean with:
> Or were you waiting to add it until you figured out why it was using a snapshot?

If you expect me to do/add something, please do not hesitaite to tell me (with enough explanations).

**Comment by mojavelinux** [comment]
I apologize for the confusion. That question was for @abelsromero.

We probably need to document the root pom.xml. You are doing it correctly by using the repositories individually. That is how it is designed. The root pom.xml is for CI to run all the projects at once to sanity check them.

We intentionally didn't setup the root pom.xml to have shared build configuration because we want the projects to work in isolation so that they are maximally useful as a reference. A mistake I see with Maven-based examples is that a lot of logic is moved to the root pom.xml and therefore it makes it unclear what is actually required if you needed to use one of the examples as a guide.

The action is for @abelsromero to add the new module to the root pom.xml when he feels it is ready. It looks like the right time to me so long as we document that you need to run `mvn` (without any goals) when running from the root.

**Comment by abelsromero** [comment]
> to add the new module to the root pom.xml when he feels it is ready

I want to test it a bit more to be sure what to write in the readme. @jmini since you started this, seems right for you to finish it updating the parent, just make sure what is the right goal to execute all projects from the parent :smile:

**Comment by mojavelinux** [comment]
:+1: 

>  just make sure what is the right goal to execute all projects from the parent 

That part I'm sure is working now. The default goal is set as compile, which will enable it to work correctly.

**Comment by jmini** [comment]
I have tried to implement the modifications discussed here in the pull request #23. Please continue the review here.

**Comment by abelsromero** [comment]
> Please continue the review here
Hope you don't mind, but I'd rather keep the conversation on the other PR. It's just a practical thing, keeping it here involves browsing to the other site to review the changes, whereas there eveyrhing is in on page.
I just updated the subject to make it clear. Is that ok for you?

**Comment by jmini** [comment]
100% agree with you... I wanted to write: "please continue the review there"
No problem either with subject update...

**Comment by jmini** [comment]
@abelsromero 
I misunderstood your comment:
> Just a small comment. I think it would be nice to add a few words in the documentation stating it uses the SPI interface. Is it possible?
> Version 1.5.2.1 of the plugn includes other options to register extensions and we may extend the examples in the future with them.

I did not add this statement when I amended the commit.
I have opened a new Pull Request to fix this: #24 

Sorry for the additional work.

**Comment by abelsromero** [comment]
> Sorry for the additional work.

:smile: No problem, this is always a pleasure.

**Comment by abelsromero** [comment]
Btw, I receive email notifications for PR and comments on this repo, so no need to post here.
Just send the PR and reference this comment there if you want.

**Pull request merged**
