### PR TITLE
Add example: PDF book with YAML theme

### PR DESCRIPTION
**Pull request by jmini**
Related discussion on the mailing list:
http://discuss.asciidoctor.org/Asciidoctor-YAML-style-file-for-PDF-and-maven-td3849.html

This solution rely on the _TorqueBox RubyGems Maven Proxy_ to set the prawn version to 2.0.2 (to support a cover image on the front page)

### CODE REVIEW

**Comment by abelsromero** [comment]
Nice example, using styles really helps adding a more professional look to generated PDFs and it's definitely something we must have. Even, with temporal workarounds.
But the way the example is presented it is hard to spot the key elements it is showing. Maybe, if we add another execution without the theme so the system genetares 2 pdfs, it will be easier to spot the improvements over a "plain" PDF. wdyt?

Also, and that's me being picky:
* Is is possible to create the `themes` folder at the same level of `docs`? It seems to me a more natural way to organize the sources.
* Can you name the project to something that highlights the `theme` component. Just pdf-book seems too generic.

**Comment by jmini** [comment]
I think I have implemented all your ideas in my new commit.

**Comment by abelsromero** [comment]
I like the resut :+1: 

But...
> I think I have implemented all your ideas in my new commit.

sounds like obeying an order, please feel free to disagree, discuss, rant, etc.

**Comment by jmini** [comment]
I liked your additional ideas (this is why it was not a problem for me to rework my pull request)... Sorry if you had the feeling that I was rude...

In addition I can tell that I really appreaciate your reviews and the quick feedback you provide.

**Comment by abelsromero** [comment]
All clear :smile: 

I leave the PR open for some time, just in case someone else wants to add extra comments.

**Comment by mojavelinux** [comment]
Nice teamwork guys! This is a great addition because people are going to want to customize the theme very soon after learning how to use Asciidoctor PDF.

**Pull request merged**
