### PR TITLE
Set asciidoctorj version to 1.5.4

### PR DESCRIPTION
**Pull request by jmini**
I have updated the examples to use the latest AsciidoctorJ version (1.5.4).

I have noticed no unexpected differences in the outputs (I have compared the HTML files between version 1.5.3.2 and 1.5.4)

### CODE REVIEW

**Comment by abelsromero** [comment]
I see it perfect

**Comment by jmini** [comment]
Wait. By doing some more investigations on twitter, I have discovered that there is more:

* `asciidoctorj-pdf` is now 1.5.0-alpha.11
* `asciidoctorj-epub3` is now 1.5.0-alpha.6

See this [twitt by Robert Panzer](https://twitter.com/bobbytank42/status/684348621752524800).

I will update my commit.

**Comment by abelsromero** [comment]
Hehe, I've been following those tweets this afternoon too, quite a lot of changes. Many things also on the JavaScript engine, but this does not affect this project.
Take your time and let me know when you're ready to merge.

**Comment by jmini** [comment]
I think my commit for yesterday can be merged. There is no example using `asciidoctorj-epub3` and the other dpendencies where updated.

**Comment by abelsromero** [comment]
Great! Thanks!
Btw, if you think the update script can be improved in any way, feel free to comment o make changes.

**Pull request merged**
