### PR TITLE
Fixes issue #22 adding a simple script to check and replace tabs

### PR DESCRIPTION
**Pull request by abelsromero**
As finally proposed in the issue, this PR includes, a small script to optionally check for tabs, and also to fix them with a parameter. It can be used as a maven profile from the parent.
Also, to document it's usage I took the liberty of copying and adapting the "Contributing" section from the asciidoctor project. I think this helps to encourage collaboration and introduces the usage of the script without forcing contributors to use it.

### CODE REVIEW

**Comment by mojavelinux** [comment]
Looks great!

Regarding the contributing section, you may be interested in what's going on in the Asciidoctor.js project. We are trying to come up with a template for information about contributing.

**Comment by mojavelinux** [comment]
See https://github.com/asciidoctor/asciidoctor.js/pull/71

**Comment by abelsromero** [comment]
> See asciidoctor/asciidoctor.js#71

Great introduction, I can surely include that as it is. But I am concerned about the long term solution. Is there a way to link it? Other than using the absolute url.

**Comment by mojavelinux** [comment]
The idea, eventually, is that these files will be managed from a build tool that pushes out updates to the repositories. That way, there's no need to include, but we also don't have a maintenance problem.

For now, just copying it into the repository is sufficient.

**Comment by abelsromero** [comment]
I guess it can be merged?

**Comment by mojavelinux** [comment]
Sure thing!

**Pull request merged**
